# Set all versions
CUSTOM_VERSION := $(PLATFORM_VERSION)-$(shell date +%Y%m%d)-pissel
CUSTOM_MOD_VERSION := aosp_$(TARGET_PRODUCT)-$(CUSTOM_VERSION)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.mod.version=$(CUSTOM_MOD_VERSION)

